config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #resources :users
  resources :concerts
  resources :concert_halls
  resources :repertoires
  resources :orchestras
  get '/', to: "concerts#index"
  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  get '/profile', to: "users#show"
  get '/edit_profile', to: "users#edit"
  post '/edit_profile', to: "users#update"
  get '/create_account', to: "users#new"
  post '/create_account', to: "users#create"
  delete '/signout', to: "sessions#destroy"
  post '/profile', to: "users#delete_concert"
  delete '/profile', to: "users#add_concert"
end

app/models/repertoire.rb
class Repertoire < ApplicationRecord
    belongs_to :concert
end

app/controllers/repertoires_controller.rb
class RepertoiresController < ApplicationController
    
    def index
       
        @repertoires = Repertoire.all
        
    end
    
    
    def show
        @repertoire = Repertoire.find_by(id: params[:id])
    end
    
end

app/helpers/repertoires_helper.rb
module RepertoiresHelper
end

app/views/repertoires/index.html.erb
<div>
<h1 class= "w3-animate-opacity">Repertoires</h1>
</div>
<ul class="w3-ul w3-hoverable">
    <% @repertoires&.each do |repertoire| %>
        <li><%= link_to repertoire.name, repertoire_path(repertoire) %></li>
    <% end %>
</ul>

app/views/repertoires/show.html.erb
<div>
    <h1 class= "w3-animate-opacity"><%= @repertoire.name %></h1>
</div>

<div class="w3-container"> 
  <h4>Composer</h4>
  <p><%= @repertoire.composer %></p>
  <hr>
</div>
<div class="w3-container"> 
  <h4>Duration</h4>
  <p><%= @repertoire.duration %> minutes</p>
  <hr>
</div>


<br>
<br>
<br>
<br>
<br>
<br>

<%= link_to "View All Repertoires", repertoires_path %>
<br>
<br>
<%= link_to "Go To Concert Page", concert_path(@repertoire.concert) %>