config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #resources :users
  resources :concerts
  resources :concert_halls
  resources :repertoires
  resources :orchestras
  get '/', to: "concerts#index"
  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  get '/profile', to: "users#show"
  get '/edit_profile', to: "users#edit"
  post '/edit_profile', to: "users#update"
  get '/create_account', to: "users#new"
  post '/create_account', to: "users#create"
  delete '/signout', to: "sessions#destroy"
  post '/profile', to: "users#delete_concert"
  delete '/profile', to: "users#add_concert"
end

app/models/concert.rb
class Concert < ApplicationRecord
    has_many :concert_users
    has_many :users, through: :concert_users
    belongs_to :orchestra
    belongs_to :concert_hall
    has_many :repertoires
    
    def format_date
        self.time.strftime("%m/%d/%Y at %I:%M%p")
    end

    def format_date_only
        self.time.strftime("%m/%d/%Y")
    end

    def format_price
        "$#{"%.2f" % self.price}"
    end

    def passed? #whether the concert already happened
        self.time < Time.now
    end

    def num_user_interested #counts the number of users added this
        ConcertUser.select{|joiner| joiner.concert==self}.count
    end

    def self.future_concerts
        self.all.select{|concert| !concert.passed?}
    end

    def self.past_concerts
        self.all.select{|concert| concert.passed?}
    end

    def self.all_concerts
        self.all
    end

    def self.get_view_list(option)
        if(option=="all")
            self.all_concerts
        elsif(option=="past")
            self.past_concerts
        else
            self.future_concerts
        end
    end

    def self.sorted_by_date_asc(option)
        self.get_view_list(option).sort_by{|concert| concert.time}
    end

    def self.sorted_by_date_dec(option)
        self.get_view_list(option).sort_by{|concert| concert.time}.reverse
    end

    def self.sorted_by_recent(option)
        #self.order(updated_at: :desc)
        self.get_view_list(option).sort_by{|concert| concert.updated_at}.reverse
    end

    def self.sorted_by_popularity(option)
        #self.all.sort{|concert| -concert.num_user_interested}
        self.get_view_list(option).sort_by{|concert| concert.num_user_interested}.reverse
    end

    def self.sorted_by_price_asc(option)
        #self.order(price: :asc)
        self.get_view_list(option).sort_by{|concert| concert.price}
    end

    def self.sorted_by_price_dec(option)
        #self.order(price: :desc)
        self.get_view_list(option).sort_by{|concert| concert.price}.reverse
    end
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
    def index
        #byebug
        @query_options=[ ["By Date (dec)", "date_dec"], ["By Date (asc)", "date_asc"], ["By Popularity", "popularity"], ["By Price (inc)", "price_asc"], ["By Price (dec)", "price_dec"], ["Most Recent", "recent"]]
        queries=@query_options.map{|option| option[1]}
        @mode="date_dec"
        @mode=params[:mode] if queries.include?(params[:mode])

        @display_options=[ ["Past Concerts", "past"], ["Upcoming Concerts", "future"], ["All Concerts", "all"]]
        displays=@display_options.map{|option| option[1]}
        @displayed="all"
        @displayed=params[:view] if displays.include?(params[:view])

        @user=current_user

        @title=@display_options.find{|option| option[1]==@displayed}[0]+" "
        case @mode
        when "popularity"
            @title+="Sorted by Popularity"
            @concerts=Concert.sorted_by_popularity(@displayed)
        when "date_dec"
            @title+="Sorted by Date (Descending)"
            @concerts=Concert.sorted_by_date_dec(@displayed)
        when "date_asc"
            @title+="Sorted by Date (Ascending)"
            @concerts=Concert.sorted_by_date_asc(@displayed)
        when "recent"
            @title+="Sorted by Recency"
            @concerts=Concert.sorted_by_recent(@displayed)
        when "price_asc"
            @title+="Sorted by Price (Lowest First)"
            @concerts=Concert.sorted_by_price_asc(@displayed)
        when "price_dec"
            @title+="Sorted by Price (Highest First)"
            @concerts=Concert.sorted_by_price_dec(@displayed)
        else
            @title = "All Concerts"    
            @concerts=Concert.all
        end
        
    end

    def show
        @concert = Concert.find_by(id: params[:id])
    end
    
    
end

app/helpers/concerts_helper.rb
module ConcertsHelper
    def concert_date_format(concert)
        created = concert.updated_at.to_datetime
        now = DateTime.now
    
        seconds = ((now - created) * 24 * 60 * 60).to_i
        minutes = seconds / 60
        hours = minutes / 60
        days = hours / 24
        months = days / 30
        years = months / 12
    
        if seconds < 60
          return "#{seconds} seconds ago"
        elsif minutes < 60
          return "#{minutes} minutes ago"
        elsif hours < 24
          return "#{hours} hours ago"
        elsif days < 30
          return "#{days} days ago"
        elsif months < 12
          return "#{months} months ago"
        else
          return "#{years} years ago"
        end
      end
end

app/views/concerts/_bill.html.erb
<script>
    console.log("bill partial")
    function changeBackgroundToRandomColor(){        
        const randomColor = Math.floor(Math.random()*16777215).toString(16);
        document.body.style.backgroundColor = "#" + randomColor;
    }

    setInterval(changeBackgroundToRandomColor, 100)

    let cards=document.getElementsByClassName('w3-card')
    let rotationMatrix=[]
    for (let i = 0; i< cards.length; i++){
        rotationMatrix.push(0)
    }


    function randomlyRotateCards(){
        let cards=document.getElementsByClassName('w3-card')
        for(let i=0; i< cards.length; i++){
            rotationMatrix[i]+=Math.floor(Math.random()*5)
            cards[i].style.transform=`rotate(${rotationMatrix[i]}deg)`
        }
    }

    setInterval(randomlyRotateCards,50)

    function changeCardsToRandomColor(){        
        let cards=document.getElementsByClassName('w3-container')
        for(let i=0; i< cards.length; i++){
            let randomColor = Math.floor(Math.random()*16777215).toString(16);
            cards[i].style.backgroundColor="#" + randomColor;
        }
    }

    setInterval(changeCardsToRandomColor,100)

    function cautionAlert(){
        alert("Don't get epilepsy pls thx")
    }

    cautionAlert()
    setInterval(cautionAlert, 10000)

    function changeCardFonts(){
        var fontTypes = [ "Arial", "Verdana", "Helvetica", "Tahoma", "Trebuchet MS", "Georgia", "Garamond", "Courier New"]
        let cardHeader = document.getElementsByTagName('h3')
        for(let i=0; i< cards.length; i++){
            let randomFont = fontTypes[Math.floor(Math.random()*fontTypes.length)]
            cardHeader[i].style.fontFamily=randomFont;
        }
    }
    setInterval(changeCardFonts,200)
</script>

app/views/concerts/index.html.erb
<h1>Browse Concerts</h1>
<%=form_tag "/concerts", :method => "get" do%>
    <%=label_tag "View Options"%>
    <%=select_tag 'mode', options_for_select(@query_options, @mode), :onchange => "this.form.submit();"%>
    <%=select_tag 'view', options_for_select(@display_options, @displayed), :onchange => "this.form.submit();"%>
<% end %>
<div class="title-container" >
    <h2 style="text-align:center"> <%=@title%> </h2>
</div>
<div class="concerts-container" style="margin:auto;">
<%@concerts&.each do |concert|%>
    <div class="w3-card w3-hover-shadow", style="max-width:600px;margin:auto;">
        <header class="w3-container w3-blue">
            <br>
            <h3 > <%= link_to concert.name, concert_path(concert), style:"color:white;" %></h3>
            <br>
        </header>
        <div class="w3-container">
            <br>
            <p> <b>Time:</b> <%=concert.format_date%><p>
            <p> <b>Price:</b> <%=concert.format_price%></p>
            <p> <b>Location:</b> <%=link_to concert.concert_hall.name+" | "+concert.concert_hall.location, concert.concert_hall%></p>
            <p> <b>Orchestra:</b> <%= link_to concert.orchestra.name, concert.orchestra %>
            <p> <b>Users interested:</b> <%=concert.num_user_interested%></p>
            <p> <b>Last updated</b> <%=concert_date_format(concert)%><p>
        
        <% if (@user)%>
            <% if(@user.has_concert?(concert))%>
                <%=form_tag '/profile', method: 'post' do%>
                    <%=hidden_field_tag 'concert_id', concert.id%>
                    <%=submit_tag "Remove From List", class: "w3-button w3-red"%>
                <% end %>
            <% else %>
                <%=form_tag '/profile', method: 'delete' do%>
                    <%=hidden_field_tag 'concert_id', concert.id%>
                    <%=submit_tag "Add To List", class: "w3-button w3-green"%>
                <% end %>
            <% end %>
        <% end %>
        </div>
        <br>
    </div>
    <br>
<% end %>
</div>

<%=render partial: "bill"%>

app/views/concerts/show.html.erb
<%# <%= image_tag "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.laphil.com%2F&psig=AOvVaw1dSTBM3Tb_BTo9GKVBVww2&ust=1626503371682000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCOCQ17H75vECFQAAAAAdAAAAABAD", style: "width:100%" %> 
<div>
    <h1 class= "w3-animate-opacity" ><%= @concert.name %></h1>
</div>

<div class="w3-container"> 
  <h4>Orchestra</h4>
  <p><%= link_to @concert.orchestra.name, orchestra_path(@concert.orchestra) %></p>
  <hr>
</div>

<div class="w3-container"> 
  <h4>Repertoires</h4>
  <p><%= link_to "All Repertoires", repertoires_path %></p>
  <hr>
</div>



<div class="w3-container"> 
  <h4>Concert Hall</h4>
  <p><%= link_to @concert.concert_hall.name, concert_hall_path(@concert.concert_hall) %></p>
  <hr>
</div>

<div class="w3-container"> 
  <h4>Date</h4>
  <p><%= @concert.format_date %></p>
  <hr>
</div>

<div class="w3-container"> 
  <h4>Ticket Price</h4>
  <p><%= @concert.format_price %></p>
  <hr>
</div>

<br>
<br>
<br>
<br>
<br>
<%= link_to "View All Concerts", concerts_path %>