config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #resources :users
  resources :concerts
  resources :concert_halls
  resources :repertoires
  resources :orchestras
  get '/', to: "concerts#index"
  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  get '/profile', to: "users#show"
  get '/edit_profile', to: "users#edit"
  post '/edit_profile', to: "users#update"
  get '/create_account', to: "users#new"
  post '/create_account', to: "users#create"
  delete '/signout', to: "sessions#destroy"
  post '/profile', to: "users#delete_concert"
  delete '/profile', to: "users#add_concert"
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light sticky-top" style="background-color: #0ebbeb;">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Concearch</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        
        <li class="nav-item">
          <%= link_to "Concerts", concerts_path, class: "nav-link active" %>
        </li>

        <li class="nav-item">
          <%= link_to "Orchestras", orchestras_path, class: "nav-link active" %>
        </li>

        <li class="nav-item">
          <%= link_to "Concert Halls", concert_halls_path, class: "nav-link active" %>
        </li>

        <li class="nav-item">
          <%= link_to "Repertoires", repertoires_path, class: "nav-link active" %>
        </li>

        <% if signed_in? %>
          <li class="nav-item">
            <%= link_to "My Profile", profile_path, class: "nav-link active" %>
          </li>
          <span class="navbar-text">
              <%="   Logged in as #{@user.full_name}"%>
          </span>
          <li class="nav-item">
            <%= button_to "Log Out", signout_path, :method => :delete , class:"btn"%>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Create Account", create_account_path, class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to "Log In", login_path, class: "nav-link active" %>
          </li>
        <% end %>
      </ul>
      
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Concearch</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> 
  </head>

  <body>
    <%= render(partial: "layouts/nav")%>
    <div class="w3-margin-left w3-margin-right">
    <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>